### ISSUE TITLE
Missing npm releases of azure-event-processor-host

### ISSUE THREAD

**Issue by jrauschenbusch** [Azure/azure-event-hubs-node#138]
**Is your feature request related to a problem? Please describe.**
Currently the latest release of azure-event-processor-host on npm is 0.1.4 while the one of azure-event-hubs is 0.2.8. Maybe the cause is the missing tracking as azure-event-processor-host is hosted in the same repository.

https://www.npmjs.com/package/azure-event-processor-host

**Describe the solution you'd like**
Please create a npm releases of azure-event-processor-host which matches the according available version of azure-event-hubs. Maybe also change the dependency inside the package.json from the relative path syntax to an absolute one. And last but not least: Please align the release cycles of both npm artefacts.

**Describe alternatives you've considered**
Create an dedicated repository for azure-event-processor-host. Then it would be possible to use gitlab dependency references.

**Comment by amarzavery** [comment]
Hi @jrauschenbusch - Thanks for filing this issue. The solution that has been checked into the master branch is decent. It works well for an EventHub with ~64 partitions. However, it does not scale well with a 256/512 partition EventHub. I am in the middle of revamping the partition management logic for EPH (Event processor host). Hence, the package was not published, the relative reference to the event hubs package was not updated and a [github release](https://github.com/Azure/azure-event-hubs-node/releases) was not created. I should have created a dev branch rather than checking things into master. Sorry for the confusion. Once things are ready 0.2.0 version of azure-event-processor-host will be published very soon. Post that things would be relatively stable and the versions would almost be in sync as you mentioned.

**Comment by jrauschenbusch** [comment]
Hi @amarzavery,

alright. What is your approx. time table for completing the EPH management logic modifications?  I think for most use cases a working release with 64 partitions is completely fine. Therefore i would say a release should not be affected by open revamping tasks. A version 0.x.x should be enough to inidicate that there is still WIP related to the stability.

One idea for the structure: If it's necessary to keep the references between the two projects (event-hubs and event-processor-host) you could maybe use the git submodule feature. Imho it would be better to have 2 separated git repos, because of the the own lifecycles and the issue management of the components.

**Comment by jrauschenbusch** [comment]
Alright! Thx for the fast treatment!
