### ISSUE TITLE
No connection handler was found for virtual host '522'.

### ISSUE THREAD

**Issue by MatejSkrbis** [Azure/azure-event-hubs-node#149]
After running receiver for some time, following temporary error is displayed: 
No connection handler was found for virtual host '522'.

Is this a thing that library should handle?
If it's not what are the possible error codes and is there any documentation about them and how to handle them?

**Comment by amarzavery** [comment]
The sdk should be handling this. What is the name and version of the package that you are using?

**Comment by MatejSkrbis** [comment]
I'm currently using "azure-event-hubs": "0.2.8"

**Comment by MatejSkrbis** [comment]
Haven't noticed that @azure/event-hubs should to be used now.
I'll try it with this latest version.

**Comment by amarzavery** [comment]
Yup was just about to say that. It would be easier to provide a resolution if you can provide debug logs, by setting the environment variable as follows

`export DEBUG=azure*,rhea*,-rhea:raw,-rhea:message,-azure:amqp-common:datatransformer`

**Comment by amarzavery** [comment]
I was looking at the source code to figure out why you are seeing this error.
I feel it's this [line of code]( https://github.com/Azure/azure-event-hubs-node/blob/master/client/lib/eventHubReceiver.ts#L227).
If an error is received and the sdk user did not close the receiver then we let the user know about it. However we will  make an attempt to reconnect if the error is retryable. 
This particular error that you are seeing is a retryable error and the sdk is retrying at an interval of 15 seconds. Usually the service comes back up under 60 seconds (once they are done moving the nodes/vms in the background). So you should see in the debug logs that the sdk is making reconnection attempts every 15 seconds. Usually under 4 or 5 attempts the receiver should be back up.

May be the sdk should not send the error to the error handler, if it is retrying to avoid confusion.

The flip side is, if the receiver is silent for a long time (15 seconds) between reconnect attempts, then the user may think that the receiver is hung, whereas it's actually retrying.
May sending the error with a message that the receiver is retrying would be a better option.

**Comment by MatejSkrbis** [comment]
I've tried to install @azure/event-hubs": "1.0.1
Now it seems that whenever I call eventHubClient.getPartitionIds(); it throws 

```
condition:"com.microsoft:timeout"
message:"The request with message_id "8015a8c3-144c-4b8d-a98d-c44fff43cdb4" to "$management" endpoint timed out. Please try again later."
name:"ServiceUnavailableError"
retryable:true
```

I'm not sure if it got anything to do with newer version or is it just some temporary thing.

**Comment by amarzavery** [comment]
I think that is a temporary thing. I just ran my tests again and they work fine. If for some reason, the sdk does not receive a response from the service then in the specified time then the request timeout happens. The attempt is made 3 times at an interval of 15 seconds and still if the operation fails then the sdk throws an error.

On a side note, you may want to try event processor host [@azure/event-processor-host](https://github.com/Azure/azure-event-hubs-node/tree/master/processor). It is an efficient message receiver. It does couple of things:
- scans partitions at regular interval to determine if a receiver should be connected to that partition
- balances the load of receiving messages from different partitions. It also balances load across different instances of EPH as well. The instances could be within the same process or different processes on the same machine or across different machines.
 
The user needs to checkpoint the messages to the storage account at regular interval, so that other instances can start their receivers from the checkpointed offset.

**Comment by amarzavery** [comment]
Hello @MatejSkrbis - How is it going? Just checking to make sure things are running smoothly.

**Comment by amarzavery** [comment]
Well having the error in the logs is fine. But did you see the sdk trying to reconnect after receiving the error?

**Comment by MatejSkrbis** [comment]
I am not 100% sure, but I think it did reconnect. There were generally no obvious problems with receiving messages. So may I just ignore this message in future, when it occurs not to spam all over the logs? Are there any other messages I can ignore and what are the error codes? 

If i would keep everything non vital in exception logs then logs wouldn't be as useful anymore for detecting other more serious problems.

**Comment by amarzavery** [comment]
I will be sending a PR tomorrow, to not bubble up retryable errors to the user if the sdk is retrying. This should avoid any confusion.

**Comment by amarzavery** [comment]
@MatejSkrbis - New version of @azure/event-hubs: 1.0.3 has been published which fixes this issue.
