### ISSUE TITLE
Event processing host errors

### ISSUE THREAD

**Issue by MatejSkrbis** [Azure/azure-event-hubs-node#159]
I've tried to use @azure/event-processor-host": "1.0.2

I've created new event hub with 32 partitions and set access policies to manage.
Then I tried to initialize 4 instances of EventProcessorHost that I created from connection string and all of them were pointing to same event hub (I think this should still work or do they need to be on separate computers or processes to test?).
I then started all 4 of them and started receiving some packets that were sent to this event hub.
Even though some packets were received there were tons of errors reported until my service crashed with `transfer after detach` error.

Here are the list of different errors I received - most of them were repeated a lot of times:

```
MessagingError: The messaging entity 'streams:eventhub:test-hub~2047|consumers' could not be found. TrackingId:93b327c5-2dab-43d7-beb8-635e6c68f53d_B17, SystemTracker:streams:eventhub:test-hub~2047|consumers, Timestamp:9/20/2018 1:39:05 PM TrackingId:012a846c3e644424a5bef547be9eeb51_G30, SystemTracker:gateway5, Timestamp:9/20/2018 1:39:05 PM

[connection-2] error on read: ProtocolError: attach received on invalid channel 2  (buffer:0x00,...)

[connection-3] error on read: ProtocolError: detach received on invalid channel 4  (buffer:0x00,...)

MessagingError: New receiver with higher epoch of '5' is created hence current receiver with epoch '4' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:ff92ddfe000003c30004c7925ba3a318_G9_B20, SystemTracker:streams:eventhub:test-hub~24575|$default, Timestamp:9/20/2018 1:39:41 PM

MessagingError: The request with message_id "706920c4-d036-415c-900a-97514c05e7bc" to "$management" endpoint timed out. Please try again later.

MessagingError: The request with message_id "340e306b-fadf-4c82-abdf-8f70b0e8273c" to "$cbs" endpoint timed out. Please try again later.

MessagingError: Unable to create the amqp receiver 7ed373cf-2922-4f7d-b271-c87daef60fdd due to operation timeout.

MessagingError: Unable to create the amqp session due to operation timeout.

MessagingError: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://streams.servicebus.windows.net/test-hub/consumergroups/consumers/partitions/17'. TrackingId:8b064d004b2f46e6bc041e7c319c6ed8_G4, SystemTracker:gateway5, Timestamp:9/20/2018 1:45:08 PM

MessagingError: A link to connection '275148' $management node has already been opened.

\event-processing-service\node_modules\rhea\lib\session.js:360
console.pub.js:42
        throw Error('transfer after detach');


```

**Comment by amarzavery** [comment]
Since node.js is single threaded, I would recommend creating different processes. In that way the event loop does not get stressed between receiving messages for all the eph instances and managing leases for them as well.

As explained in the [overview doc](https://github.com/Azure/azure-event-hubs-node/blob/master/processor/overview.md#internal-working-of-event-processor-host), eph uses the epoch receiver feature of event hubs. This allows EPH to ensure that at any given time, only 1 receiver will be actively listening from a partition within the provided consumer group.

Hence, this error
```
MessagingError: New receiver with higher epoch of '5' is created hence current receiver with epoch '4' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:ff92ddfe000003c30004c7925ba3a318_G9_B20, SystemTracker:streams:eventhub:test-hub~24575|$default, Timestamp:9/20/2018 1:39:41 PM
```
makes sense. Because another EPH instance was trying to load balance, it created an epoch receiver with a higher epoch value, which caused the receiver from the previous EPH to get disconnected. I will send a PR to not bubble up such errors as well. This should avoid confusion.

```
MessagingError: The messaging entity 'streams:eventhub:test-hub~2047|consumers' could not be found. TrackingId:93b327c5-2dab-43d7-beb8-635e6c68f53d_B17, SystemTracker:streams:eventhub:test-hub~2047|consumers, Timestamp:9/20/2018 1:39:05 PM TrackingId:012a846c3e644424a5bef547be9eeb51_G30, SystemTracker:gateway5, Timestamp:9/20/2018 1:39:05 PM
```
AZ:  This looks like it was not able to find the event hub.

```
[connection-2] error on read: ProtocolError: attach received on invalid channel 2  (buffer:0x00,...)

[connection-3] error on read: ProtocolError: detach received on invalid channel 4  (buffer:0x00,...)
```
AZ: Would look into these two. It looks like a lower level protocol error.

```
MessagingError: The request with message_id "706920c4-d036-415c-900a-97514c05e7bc" to "$management" endpoint timed out. Please try again later.

MessagingError: The request with message_id "340e306b-fadf-4c82-abdf-8f70b0e8273c" to "$cbs" endpoint timed out. Please try again later.

MessagingError: Unable to create the amqp receiver 7ed373cf-2922-4f7d-b271-c87daef60fdd due to operation timeout.

MessagingError: Unable to create the amqp session due to operation timeout.
```
AZ: These errors are due to everything being run in the same process. The event loop is busy doing too many things. Hence the operations timeout.

```
MessagingError: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://streams.servicebus.windows.net/test-hub/consumergroups/consumers/partitions/17'. TrackingId:8b064d004b2f46e6bc041e7c319c6ed8_G4, SystemTracker:gateway5, Timestamp:9/20/2018 1:45:08 PM
```
AZ: This one looks like the cbs token expired and the client was not able to renew token. Token renewal happens at an interval of 45 minutes (token expires in 60 minutes). Which again indicates that the event loop was busy doing too many things.
```
MessagingError: A link to connection '275148' $management node has already been opened.

\event-processing-service\node_modules\rhea\lib\session.js:360
console.pub.js:42
        throw Error('transfer after detach');
```
AZ: This error should not have happened. Will have to investigate further.

**Comment by amarzavery** [comment]
@MatejSkrbis - New version of @azure/event-processor-host: 1.0.3 has been published which fixes this issue.

**Comment by ramya-rao-a** [comment]
Closing this issue as fixed.
