### ISSUE TITLE
Release numbers are confusing

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-event-hubs-node#3]
_From @shpros on November 8, 2016 23:39_

As of this writing, [NPM](https://www.npmjs.com/package/azure-event-hubs) says `0.0.4 is the latest of 4 releases`, but the [releases](https://github.com/Azure/azure-event-hubs/releases) tab of this GitHub project says that `v0.8.0` is the most recent of 14 releases going back to `v0.3.0`. 

1. Why do the release numbers change so drastically between GitHub and NPM?
2. We are currently using NPM release 0.0.3 but ought to be moving to 0.0.4. So that we can determine what has changed, to which GitHub releases do the NPM releases 0.0.3 and 0.0.4 correspond?

_Copied from original issue: Azure/azure-event-hubs#292_

**Comment by pierreca** [comment]
True - The reason is that multiple SDKs were shipped from the same Github Repo (the generic https://github.com/Azure/azure-event-hubs).

Now that each SDK has its own repository, things should get better.

Right now the convention is to tag a new release with the date (2017-3-29 for example) and include the NPM package version in the title. This is aligned with what's done for the Azure IoT Hub SDK and takes into account the fact that multiple NPM packages with different versions may be shipped from the same repository. Hopefully we can make our release notes can provide the necessary explanations to not make this confusing.

As of now there is no plan to split further and have a 1-to-1 match between repos and packages.
