### ISSUE TITLE
Does PartitionKey represents the name of the key or its value ?

### ISSUE THREAD

**Issue by yanisIk** [Azure/azure-event-hubs-node#72]
My eventhub has 32 partitions.
My events are sent in the following format: `{body: encodedData, partitionKey: "groupName"};`
`groupName` represents the name of the field that should be used as a partitionKey.

Is this the right way or should I use the value of the key ?

I'm asking because when sampling data from eventhub, I found that the same key was in two different partitions.

Also, what happens when I don't have 32 different groups ? How the rest of the partitions get filled ?

Thanks.

**Comment by amarzavery** [comment]
> My events are sent in the following format: {body: encodedData, partitionKey: "groupName"};
groupName represents the name of the field that should be used as a partitionKey.
 Is this the right way or should I use the value of the key ?

It does not matter what value you provide to the partition key. Eventhub is supposed to hash that value and send it to a particular partition. As long as you send the same partition key, the hashing function on the server side should result in sending the event to the same partition.

> I'm asking because when sampling data from eventhub, I found that the same key was in two different partitions.

I have seen this issue with Eventhubs. I have a test for this, which fails. I am in touch with the service team to figure out the root cause.

> Also, what happens when I don't have 32 different groups ? 
By this are you referring to partitions or consumer groups. If you are referring to consumer groups then Eventhubs by default creates a `"$default"` consumer group. You can create more consumer groups if you wish to.

If you were referring to `32 different groups` as 32 different **partitions** then when you create the EventHub using the management plane sdk (azure-**arm**-eventhub) or via the portal, you need to create a hub with atleast 2 partitions. I mean the portal wont allow you to create a hub with 0 partitions.

> How the rest of the partitions get filled ?

If you don't provide the partition id or the partition key then the service will store the messages in a round robin fashion between the partitions in the event hub.

**Comment by yanisIk** [comment]
Thanks @amarzavery 

I think you didn't understand my first question.
I'm wondering what I should send in the partitionKey field: The name of the key (that refers to the key that should be used in the eventData) or its value.

For example, if I want to partition by "Car Make" and that my data looks like: `{make: "Toyota", licensePlate: "1234"}`

Should I send `{body: carObject, partitionKey: "make"} `or `{body: carObject, partitionKey: carObject.make}` ?

**Comment by amarzavery** [comment]
I did understand your question. Sorry I did not not conclude my explanation.

Event hub is supposed to hash that value and send it to a particular partition. As long as you send the same partition key, the hashing function on the server side should result in sending the event to the same partition.

So if you want cars of a particular make to be sent to a particular partition then you should be sending the value of the make as that partition key. For instance all messages where car make is "toyota" should go to a particular partition and all messages where the car make is "honda" should go to a specific partition then you should be sending "toyota" and "honda" as the partition key (i.e. carObject.make).

**Comment by yanisIk** [comment]
Thanks a lot !
