### ISSUE TITLE
Add support for diagnostic tracing.

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-event-hubs-node#86]
- Look at different options Open census, Azure App insights with plugins for bunyan.

.NET ServiceBus and EventHubs SDKs have done instrumentation with DiagnosticSource (analog of the diagnostic channel).
From .NET clients some information is also sent to correlate producer and consumer. 
 
The protocol is described here: https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-end-to-end-tracing

It would be nice if node.js and other lang sdks can follow the same protocol.

**Comment by lmolkova** [comment]
Here is the instrumentation code (just for reference):

* EH: https://github.com/Azure/azure-event-hubs-dotnet/blob/dev/src/Microsoft.Azure.EventHubs/EventDataDiagnosticExtensions.cs

* SB: https://github.com/Azure/azure-service-bus-dotnet/blob/dev/src/Microsoft.Azure.ServiceBus/ServiceBusDiagnosticsSource.cs

**Comment by amarzavery** [comment]
@devigned - I know that Go EH and SB Sdks have used open tracing with Jaeger for diagnostics. However, please feel free to share your thoughts on this.
/cc @annatisch

**Comment by lmolkova** [comment]
diagnostic channel provides a great level of abstraction so it could be consumed by opentracing implementation or any other system.

Microsoft [has recently joined OpenCensus project](https://open.microsoft.com/2018/06/13/microsoft-joins-the-opencensus-project/) project and that's the Azure direction for distributed tracing.

Opencensus is similar to Opentracing and is also going to benefit from the diagnostic channel in node.

**Comment by devigned** [comment]
I need to do a bit more research into how I'd accommodate OpenCensus message propagation on AMQP messages, but it seems like it should operate similarly to the OpenTracing solution we have in place currently.

I do worry about how wide reaching the adoption of OT is vs OC (trends: https://trends.google.com/trends/explore?q=opentracing,opencensus, developers: https://github.com/census-instrumentation/opencensus-java/issues/482#issuecomment-380833020, CNCF adoption, etc.). There are many tools that already work with OT. I see one of the biggest reasons to choose an open implementation of tracing is the existing set of customers using that implementation and then experiencing the "I just got tracing and metrics for free!" when using our libraries.

@lmolkova do you have any thoughts on this?

**Comment by lmolkova** [comment]
The propagation standard is not covered by OT or OC to the best of my knowledge.
However there is an evolving W3C RPC propagation standard https://github.com/w3c/distributed-tracing, the whole .NET stack will be moving to it a few months. 
However for now, perhaps it's a good idea to have the same propagation protocol as .NET SDKs so that we can have the end-to-end story, how we can correlate producers and consumers in different languages. 

Regarding using OT vs OC API. The tools you are referring to (I assume) are tracing systems like jaeger. They consume any source of instrumentation and Jaeger is one of the projects behind OpenCensus. 

And the diagnostic channel is a library instrumentation API - any tracing system could consume it, 
there is an effort to bake diagnostic-channel into the node so it becomes a default way to instrument any library. 

@mike-kaufman and @OsvaldoRosado can provide more details on that.

**Comment by mike-kaufman** [comment]
RE diagnostics-channel & getting it into node, the intent has been to have diagnostics-channel or some equivalent get adopted by various APM vendors & library providers, with the goal being to eliminate monkey-patching that APM vendors tend to do.  If done correctly, this shoudl allow any anyone interested to layer on top and transform the events from diag-channel into open tracing or open census or whatever.  Now, the reality is, outside of general agreement on the direction here, there's been very limited progress on making this a reality.  

Happy to answer ?s here, and help plug people into this effort in the node.js community if there's interest in moving it forward.

**Comment by ramya-rao-a** [comment]
cc @bterlson

**Comment by ramya-rao-a** [comment]
There will be a more centralized effort regarding diagnostic tracing in https://github.com/Azure/azure-sdk-for-js. Closing this issue in favor of those efforts now that this project has moved over there.
